const map=L.map('map',{zoomControl:false,preferCanvas:true}).setView([33.5902,130.4017],15);
L.control.zoom({position:'bottomright'}).addTo(map);
L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap contributors'}).addTo(map);

const els={load:document.getElementById('loadAreaButton'),status:document.getElementById('status'),sheet:document.getElementById('topicSheet'),handle:document.getElementById('sheetHandle'),count:document.getElementById('sheetCount'),list:document.getElementById('topicList'),selection:document.getElementById('selectionBar'),selectionText:document.getElementById('selectionText'),clear:document.getElementById('clearSelectionButton'),tabs:[...document.querySelectorAll('.sheet-tab')]};
const markerLayer=L.layerGroup().addTo(map);
let places=[],topics=[],selectedTopic=null,displayPlaces=[],activeTab='topics',selectionToken=0;
const articleCache=new Map(),linkPlaceCache=new Map(),textPlaceCache=new Map();
const markerIcon=L.divIcon({className:'',html:'<div class="wiki-marker"></div>',iconSize:[12,12],iconAnchor:[6,6]});
const relatedIcon=L.divIcon({className:'',html:'<div class="wiki-marker related-marker"></div>',iconSize:[14,14],iconAnchor:[7,7]});
const textIcon=L.divIcon({className:'',html:'<div class="wiki-marker text-marker"></div>',iconSize:[14,14],iconAnchor:[7,7]});
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
function setStatus(text){els.status.textContent=text}
function wikidataUrl(qid){return `https://www.wikidata.org/wiki/${encodeURIComponent(qid)}`}
function wikipediaUrl(title){return `https://ja.wikipedia.org/wiki/${encodeURIComponent(title.replace(/ /g,'_'))}`}
function escapeHtml(s=''){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
async function fetchJson(url,options={}){const r=await fetch(url,options);if(!r.ok)throw new Error(`${r.status} ${r.statusText}`);return r.json()}

async function fetchWikidataPlaces(bounds){const sw=bounds.getSouthWest(),ne=bounds.getNorthEast();const query=`SELECT ?item ?itemLabel ?article ?location WHERE {\n SERVICE wikibase:box { ?item wdt:P625 ?location . bd:serviceParam wikibase:cornerWest \"Point(${sw.lng} ${sw.lat})\"^^geo:wktLiteral . bd:serviceParam wikibase:cornerEast \"Point(${ne.lng} ${ne.lat})\"^^geo:wktLiteral . }\n OPTIONAL { ?article schema:about ?item ; schema:isPartOf <https://ja.wikipedia.org/> . }\n SERVICE wikibase:label { bd:serviceParam wikibase:language \"ja\". }\n}\nLIMIT 1000`;const data=await fetchJson('https://query.wikidata.org/sparql?format=json&query='+encodeURIComponent(query),{headers:{Accept:'application/sparql-results+json'}}),byId=new Map();for(const row of data.results.bindings){const qid=row.item.value.split('/').pop(),m=row.location.value.match(/Point\(([-\d.]+) ([-\d.]+)\)/);if(!m)continue;const p=byId.get(qid)||{qid,title:row.itemLabel?.value||qid,lat:+m[2],lng:+m[1],wikiTitle:null,links:new Set(),contexts:new Map(),source:'local'};if(row.article?.value)p.wikiTitle=decodeURIComponent(row.article.value.split('/wiki/')[1]||'').replace(/_/g,' ');byId.set(qid,p)}return [...byId.values()]}
async function fetchPageLinks(title){const links=new Set();let cont=null;for(let page=0;page<12;page++){const params=new URLSearchParams({action:'query',format:'json',origin:'*',prop:'links',titles:title,plnamespace:'0',pllimit:'max'});if(cont)params.set('plcontinue',cont);const data=await fetchJson('https://ja.wikipedia.org/w/api.php?'+params),obj=Object.values(data.query?.pages||{})[0];for(const link of obj?.links||[])links.add(link.title);cont=data.continue?.plcontinue;if(!cont)break}return links}
async function enrichWikipediaLinks(items){const withWiki=items.filter(p=>p.wikiTitle);for(let i=0;i<withWiki.length;i+=4){const batch=withWiki.slice(i,i+4);setStatus(`Wikipediaリンクを取得中 ${Math.min(i+batch.length,withWiki.length)}/${withWiki.length}`);await Promise.all(batch.map(async p=>{try{p.links=await fetchPageLinks(p.wikiTitle)}catch(e){console.warn(e)}}));if(i+4<withWiki.length)await sleep(60)}}
function buildTopics(items){const counts=new Map();for(const p of items)for(const title of p.links){const entry=counts.get(title)||{title,count:0,placeIds:[]};entry.count++;entry.placeIds.push(p.qid);counts.set(title,entry)}return [...counts.values()].sort((a,b)=>b.count-a.count||a.title.localeCompare(b.title,'ja'))}

async function fetchArticle(topicTitle){if(articleCache.has(topicTitle))return articleCache.get(topicTitle);const params=new URLSearchParams({action:'parse',format:'json',origin:'*',page:topicTitle,prop:'text|links',disableeditsection:'1'}),data=await fetchJson('https://ja.wikipedia.org/w/api.php?'+params),html=data.parse?.text?.['*']||'',links=(data.parse?.links||[]).filter(x=>x.ns===0&&x.exists!==undefined).map(x=>x['*']);const doc=new DOMParser().parseFromString(html,'text/html');doc.querySelectorAll('table,style,script,sup,.mw-editsection,.navbox,.infobox').forEach(n=>n.remove());const text=doc.body?.textContent.replace(/\[[^\]]*\]/g,'').replace(/\s+/g,' ').trim()||'';const result={html,links:[...new Set(links)],text};articleCache.set(topicTitle,result);return result}
async function coordinatesForTitles(titles,source,topicTitle,token){const found=[];for(let i=0;i<titles.length;i+=50){if(token!==selectionToken)return [];const batch=titles.slice(i,i+50);setStatus(`${topicTitle}：${source==='link'?'リンク':'テキスト候補'}を照合中 ${Math.min(i+batch.length,titles.length)}/${titles.length}`);const params=new URLSearchParams({action:'query',format:'json',origin:'*',prop:'coordinates|pageprops',ppprop:'wikibase_item',colimit:'max',redirects:'1',titles:batch.join('|')}),data=await fetchJson('https://ja.wikipedia.org/w/api.php?'+params);for(const page of Object.values(data.query?.pages||{})){const c=page.coordinates?.[0];if(!c)continue;found.push({qid:page.pageprops?.wikibase_item||`page-${page.pageid}`,title:page.title,lat:c.lat,lng:c.lon,wikiTitle:page.title,links:new Set(),contexts:new Map(),source})}if(i+50<titles.length)await sleep(35)}return dedupePlaces(found)}
function dedupePlaces(items){const seen=new Set();return items.filter(p=>{const k=p.qid||`${p.lat},${p.lng},${p.title}`;if(seen.has(k))return false;seen.add(k);return true})}
function extractTextCandidates(text,linkedTitles){const linked=new Set(linkedTitles),out=new Set();const patterns=[/[一-龠々ヶヵぁ-んァ-ヶA-Za-z0-9・ー]{2,28}(?:城跡|城|館跡|館|陣跡|陣屋|屋敷跡|屋敷|御殿|門跡|門|櫓|砦|台場|寺院|寺|神社|神宮|宮|社|教会|墓地|墓所|古墳|遺跡|史跡|跡地|公園|庭園|港|港湾|駅|街道|通り|商店街|市場|町|村|郡|区|市|県|国)/g,/[一-龠々ヶヵぁ-んァ-ヶA-Za-z0-9・ー]{2,24}(?:山|川|河|池|湖|島|湾|岬)/g];for(const re of patterns){for(const m of text.matchAll(re)){let s=m[0].replace(/^[のをにはがとでへよりから]+/,'').trim();if(s.length<2||s.length>30||linked.has(s)||/^\d+年$/.test(s))continue;out.add(s);if(out.size>=350)return [...out]}}return [...out]}
async function searchCandidateTitles(candidates,topicTitle,token){const titles=new Set();for(let i=0;i<candidates.length;i+=12){if(token!==selectionToken)return [];const batch=candidates.slice(i,i+12);setStatus(`${topicTitle}：本文候補を検索中 ${Math.min(i+batch.length,candidates.length)}/${candidates.length}`);await Promise.all(batch.map(async q=>{try{const params=new URLSearchParams({action:'query',format:'json',origin:'*',list:'search',srsearch:`\"${q}\"`,srnamespace:'0',srlimit:'3'}),data=await fetchJson('https://ja.wikipedia.org/w/api.php?'+params);for(const r of data.query?.search||[])titles.add(r.title)}catch(e){console.warn('candidate',q,e)}}));if(i+12<candidates.length)await sleep(45);if(titles.size>=500)break}return [...titles]}

async function loadLinkTab(){if(!selectedTopic)return;const token=++selectionToken;activeTab='links';updateTabs();renderPanelMessage('記事内リンクから、位置情報のある項目を探しています…');try{if(linkPlaceCache.has(selectedTopic.title)){displayPlaces=linkPlaceCache.get(selectedTopic.title);finishRelatedTab('リンク',displayPlaces);return}const article=await fetchArticle(selectedTopic.title);if(token!==selectionToken)return;const result=await coordinatesForTitles(article.links,'link',selectedTopic.title,token);if(token!==selectionToken)return;linkPlaceCache.set(selectedTopic.title,result);displayPlaces=result;finishRelatedTab('リンク',result)}catch(e){console.error(e);renderPanelMessage('この記事のリンクを取得できませんでした。');setStatus('リンクの取得に失敗しました。')}}
async function loadTextTab(){if(!selectedTopic)return;const token=++selectionToken;activeTab='text';updateTabs();renderPanelMessage('本文から地名・施設名の候補を探しています…');try{if(textPlaceCache.has(selectedTopic.title)){displayPlaces=textPlaceCache.get(selectedTopic.title);finishRelatedTab('テキスト候補',displayPlaces);return}const article=await fetchArticle(selectedTopic.title);if(token!==selectionToken)return;const candidates=extractTextCandidates(article.text,article.links);const searched=await searchCandidateTitles(candidates,selectedTopic.title,token);if(token!==selectionToken)return;const result=await coordinatesForTitles(searched,'text',selectedTopic.title,token);if(token!==selectionToken)return;textPlaceCache.set(selectedTopic.title,result);displayPlaces=result;finishRelatedTab('テキスト候補',result)}catch(e){console.error(e);renderPanelMessage('本文候補を取得できませんでした。');setStatus('テキスト候補の取得に失敗しました。')}}
function finishRelatedTab(label,result){renderRelatedList(result);renderMarkers();setStatus(`${selectedTopic.title}：${label} ${result.length}地点`);fitResults(result)}
function fitResults(items){if(!items.length)return;const b=L.latLngBounds(items.map(p=>[p.lat,p.lng]));if(b.isValid())map.fitBounds(b.pad(.12),{maxZoom:15})}

async function fetchTopicContext(place,topicTitle){if(!place.wikiTitle)return '';if(place.contexts.has(topicTitle))return place.contexts.get(topicTitle);const params=new URLSearchParams({action:'parse',format:'json',origin:'*',page:place.wikiTitle,prop:'text',disableeditsection:'1'});try{const data=await fetchJson('https://ja.wikipedia.org/w/api.php?'+params),doc=new DOMParser().parseFromString(data.parse?.text?.['*']||'','text/html');let context='';for(const a of doc.querySelectorAll('a')){const href=a.getAttribute('href')||'',title=a.getAttribute('title')||'',target=decodeURIComponent(href.split('/wiki/')[1]||'').split('#')[0].replace(/_/g,' ');if(title===topicTitle||target===topicTitle){const block=a.closest('p,li,dd,td');if(block){const text=block.textContent.replace(/\[[^\]]*\]/g,'').replace(/\s+/g,' ').trim();if(text.length>=20){context=text.length>260?text.slice(0,257)+'…':text;break}}}}place.contexts.set(topicTitle,context);return context}catch(e){place.contexts.set(topicTitle,'');return ''}}
function popupHtml(p){const wiki=p.wikiTitle?`<a href="${wikipediaUrl(p.wikiTitle)}" target="_blank" rel="noopener">Wikipedia</a>`:'',wd=p.qid?.startsWith('Q')?`<a href="${wikidataUrl(p.qid)}" target="_blank" rel="noopener">Wikidata</a>`:'',google=`<a href="https://www.google.com/maps/search/?api=1&query=${p.lat},${p.lng}" target="_blank" rel="noopener">Google Maps</a>`;return `<div class="place-popup-title">${escapeHtml(p.title)}</div><div class="place-popup-meta">${p.source==='link'?'記事内リンク':p.source==='text'?'本文候補':escapeHtml(p.qid||'')}</div><div class="place-popup-links">${wiki}${wd}${google}</div>`}
function renderMarkers(){markerLayer.clearLayers();for(const p of displayPlaces){const icon=p.source==='link'?relatedIcon:p.source==='text'?textIcon:markerIcon;L.marker([p.lat,p.lng],{icon,title:p.title}).bindPopup(()=>popupHtml(p),{maxWidth:330}).addTo(markerLayer)}}
function renderTopics(){els.list.replaceChildren();els.count.textContent=topics.length?`${topics.length}件`:'';if(!topics.length){renderPanelMessage('トピックが見つかりませんでした。');return}for(const t of topics){const b=document.createElement('button');b.type='button';b.className='topic-chip';b.textContent=`${t.title} ${t.count}`;if(selectedTopic?.title===t.title)b.classList.add('active');b.addEventListener('click',()=>selectTopic(t));els.list.append(b)}}
function renderRelatedList(items){els.list.replaceChildren();els.count.textContent=`${items.length}件`;if(!items.length){renderPanelMessage('位置情報まで確認できる候補は見つかりませんでした。');return}for(const p of items){const b=document.createElement('button');b.type='button';b.className='topic-chip related-chip';b.textContent=p.title;b.addEventListener('click',()=>{map.setView([p.lat,p.lng],Math.max(map.getZoom(),16));for(const layer of markerLayer.getLayers()){if(layer.getLatLng&&layer.getLatLng().lat===p.lat&&layer.getLatLng().lng===p.lng){layer.openPopup();break}}});els.list.append(b)}}
function renderPanelMessage(text){els.list.replaceChildren();const d=document.createElement('div');d.className='panel-message';d.textContent=text;els.list.append(d)}
function updateTabs(){for(const b of els.tabs){b.classList.toggle('active',b.dataset.tab===activeTab);b.disabled=b.dataset.tab!=='topics'&&!selectedTopic}els.handle.querySelector('#sheetTitle').textContent=activeTab==='topics'?'この周辺のトピック':selectedTopic?selectedTopic.title:'トピックを選択'}
function showTopics(){selectionToken++;activeTab='topics';displayPlaces=selectedTopic?localPlacesForTopic(selectedTopic):places;updateTabs();renderTopics();renderMarkers();setStatus(selectedTopic?`${selectedTopic.title}：この範囲 ${displayPlaces.length}地点`:`${places.length}地点・${topics.length}トピック`)}
function localPlacesForTopic(topic){const ids=new Set(topic.placeIds);return places.filter(p=>ids.has(p.qid))}
function selectTopic(topic){selectionToken++;selectedTopic=topic;activeTab='topics';displayPlaces=localPlacesForTopic(topic);els.selection.hidden=false;els.selectionText.textContent=topic.title;updateTabs();renderTopics();renderMarkers();setStatus(`${topic.title}：この範囲 ${displayPlaces.length}地点`)}
function clearTopic(){selectionToken++;selectedTopic=null;activeTab='topics';displayPlaces=places;els.selection.hidden=true;updateTabs();renderTopics();renderMarkers();setStatus(`${places.length}地点を表示中`)}
async function loadArea(){selectionToken++;els.load.disabled=true;els.load.textContent='読み込み中…';selectedTopic=null;activeTab='topics';els.selection.hidden=true;els.sheet.classList.remove('open');try{setStatus('Wikidataから地点を取得中…');places=await fetchWikidataPlaces(map.getBounds());displayPlaces=places;renderMarkers();const wikiCount=places.filter(p=>p.wikiTitle).length;setStatus(`${places.length}地点 / Wikipedia ${wikiCount}記事`);await enrichWikipediaLinks(places);topics=buildTopics(places);updateTabs();renderTopics();renderMarkers();setStatus(`${places.length}地点・${topics.length}トピック`);els.sheet.classList.remove('has-results');void els.sheet.offsetWidth;els.sheet.classList.add('has-results')}catch(e){console.error(e);setStatus('読み込みに失敗しました。範囲を少し狭めて再試行してください。')}finally{els.load.disabled=false;els.load.textContent='この範囲を読み込む'}}
els.load.addEventListener('click',loadArea);els.handle.addEventListener('click',()=>{const open=els.sheet.classList.toggle('open');els.handle.setAttribute('aria-expanded',String(open))});els.clear.addEventListener('click',clearTopic);for(const b of els.tabs)b.addEventListener('click',()=>{if(b.dataset.tab==='topics')showTopics();else if(b.dataset.tab==='links')loadLinkTab();else loadTextTab()});map.on('movestart',()=>{if(!els.load.disabled&&!selectedTopic)setStatus('移動後「この範囲を読み込む」で更新')});updateTabs();
